name: Update website
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  # allow workflow to run manually
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # checkout repository
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      # List files
      - name: List repo content
        run: ls
      # Copy README.md to index.md
      - name: Copy README file content
        id: copy-readme-file
        run: cp -rf README.md index.md
      # List files
      - name: List repo content
        run: ls
      # Update md file
      - name: Update markup files in the repository
        run:  |
          git config --global user.name 'Rajaram Kaliyaperumal'
          git config --global user.email 'rr.kaliyaperumal@gmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.GIT_TOKEN }}@github.com/${{ github.repository }}
          git add index.md
          git commit -m '[automated commit] updated all website files'
          git push
